spring.application.name=applicationcompass

spring.datasource.url=jdbc:postgresql://localhost:5435/applicationcompass
spring.datasource.username=compass
spring.datasource.password=compass

spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml


